apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pale-2
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/dev/srvpale2
        mountPath: /secrets/serviceuser
      - kvPath: /kv/preprod/fss/pale-2/teamsykmelding
        mountPath: /var/run/secrets/nais.io/vault
  webproxy: true
  kafka:
    pool: nav-dev
  envFrom:
    - secret: pale-2-redis-password
  ingresses:
    - "https://pale-2.nais.preprod.local"
  env:
    - name: MQ_INPUT_QUEUE_NAME
      value: QA.Q1_PALE.INPUT
    - name: MQ_HOST_NAME
      value: b27apvl222.preprod.local
    - name: MQ_PORT
      value: '1413'
    - name: MQ_GATEWAY_NAME
      value: MQLS04
    - name: MQ_CHANNEL_NAME
      value: Q1_PALE_2
    - name: MQ_APPREC_QUEUE_NAME
      value: QA.Q414.IU03_UTSENDING
    - name: MQ_INPUT_BOQ_QUEUE_NAME
      value: Q1_PALE_2.INPUT_BOQ
    - name: ARENA_OUTBOUND_QUEUENAME
      value: QA.Q1_414.FS06_ARENA
    - name: SUBSCRIPTION_ENDPOINT_URL
      value: https://wasapp-q1.adeo.no/nav-emottak-eletter-web/services/
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.nais.preprod.local/graphql
    - name: PALE_2_REGLER_ENDPOINT_URL
      value: https://pale-2-regler.nais.preprod.local
    - name: PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
    - name: PALE_VEDLEGG_BUCKET_NAME
      value: teamsykmelding-pale2-vedlegg-bucket-dev
    - name: PALE_BUCKET_NAME
      value: teamsykmelding-pale2-legeerklaring-bucket-dev
    - name: KUHR_SAR_API_SCOPE
      value: api://dev-fss.teamkuhr.kuhr-sar-api/.default
    - name: KUHR_SAR_API_URL
      value: https://kuhr-sar-api.dev.adeo.no
