apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pale-2
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  gcp:
    sqlInstances:
      - name: pale-2-instance
        type: POSTGRES_14
        diskSize: 10
        databases:
          - name: pale-2
            envVarPrefix: DB
        diskAutoresize: true
        highAvailability: false
        diskType: SSD
        insights:
          enabled: true
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  accessPolicy:
    outbound:
      rules:
        - application: pale-2-redis
        - application: pale-2-regler
        - application: clamav
          namespace: clamav
  vault:
    enabled: false
  webproxy: false
  kafka:
    pool: nav-dev
  envFrom:
    - secret: pale-2-redis-password
    - secret: srvpale2-secrets
    - secret: pale2-keystore-pwd
  filesFrom:
    - mountPath: /var/run/secrets
      secret: pale2-google-creds
    - mountPath: /var/run/keystore
      secret: pale2-keystore
  secureLogs:
    enabled: true
  env:
    - name: MQ_INPUT_QUEUE_NAME
      value: QA.Q1_PALE.INPUT
    - name: MQ_HOST_NAME
      value: b27apvl222.preprod.local
    - name: MQ_PORT
      value: '1413'
    - name: MQ_GATEWAY_NAME
      value: MQLS04
    - name: MQ_CHANNEL_NAME
      value: Q1_PALE_2
    - name: MQ_APPREC_QUEUE_NAME
      value: QA.Q414.IU03_UTSENDING
    - name: MQ_INPUT_BOQ_QUEUE_NAME
      value: Q1_PALE_2.INPUT_BOQ
    - name: ARENA_OUTBOUND_QUEUENAME
      value: QA.Q1_414.FS06_ARENA
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
    - name: PALE_VEDLEGG_BUCKET_NAME
      value: teamsykmelding-pale2-vedlegg-bucket-dev
    - name: PALE_BUCKET_NAME
      value: teamsykmelding-pale2-legeerklaring-bucket-dev
    - name: SMGCP_PROXY_SCOPE
      value: api://dev-fss.teamsykmelding.smgcp-proxy/.default
    - name: SMGCP_PROXY_URL
      value: https://smgcp-proxy.dev-fss-pub.nais.io
    - name: PALE_2_REGLER_API_SCOPE
      value: api://dev-gcp.teamsykmelding.pale-2-regler/.default
    - name: MQ_KEYSTORE_PATH
      value: /var/run/keystore/pale2-keystore.jks
