apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pale-2
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 768Mi
  azure:
    application:
      enabled: true
      tenant: nav.no
  accessPolicy:
    outbound:
      rules:
        - application: pale-2-redis
        - application: pale-2-regler
  vault:
    enabled: false
  webproxy: false
  kafka:
    pool: nav-prod
  envFrom:
    - secret: pale-2-redis-password
    - secret: srvpale2-secrets
    - secret: pale2-keystore-pwd
  filesFrom:
    - mountPath: /var/run/secrets
      secret: pale2-google-creds
    - mountPath: /var/run/keystore
      secret: pale2-keystore
  secureLogs:
    enabled: true
  env:
    - name: MQ_INPUT_QUEUE_NAME
      value: QA.P_PALE.INPUT
    - name: MQ_HOST_NAME
      value: mpls04.adeo.no
    - name: MQ_PORT
      value: '1414'
    - name: MQ_GATEWAY_NAME
      value: MPLS04
    - name: MQ_CHANNEL_NAME
      value: P_PALE_2
    - name: MQ_APPREC_QUEUE_NAME
      value: QA.P414.IU03_UTSENDING
    - name: MQ_INPUT_BOQ_QUEUE_NAME
      value: QA.P_PALE_2.INPUT_BOQ
    - name: ARENA_OUTBOUND_QUEUENAME
      value: QA.P414.FS06_ARENA
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.prod-fss-pub.nais.io/graphql
    - name: PDL_SCOPE
      value: api://prod-fss.pdl.pdl-api/.default
    - name: PALE_VEDLEGG_BUCKET_NAME
      value: teamsykmelding-pale2-vedlegg-bucket-prod
    - name: PALE_BUCKET_NAME
      value: teamsykmelding-pale2-legeerklaring-bucket-prod
    - name: SMGCP_PROXY_SCOPE
      value: api://prod-fss.teamsykmelding.smgcp-proxy/.default
    - name: SMGCP_PROXY_URL
      value: https://smgcp-proxy.prod-fss-pub.nais.io
    - name: PALE_2_REGLER_API_SCOPE
      value: api://prod-gcp.teamsykmelding.pale-2-regler/.default
    - name: MQ_KEYSTORE_PATH
      value: /var/run/keystore/pale2-keystore.jks